### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by aikrana** [ovidiusimionica/dongle_learning_cdc#1]
Hi.
I'm having errors compiling the project. Could this be due to SDK version mismatch? What version where you using?
Thanks in advance

"make all" output:
`
/workspace/nrfspace/arm_segger_embedded_studio_v534a_linux_x64_nordic/bin/emBuild -config "Release"  -rebuild -packagesdir /workspace/nrfspace/nrf5/nRF5_SDK_17.0.2 ses.emProject
In file included from /workspace/nrfspace/nrf5/nRF5_SDK_17.0.2/components/libraries/usbd/app_usbd_core.h:48,
                 from /workspace/nrfspace/nrf5/nRF5_SDK_17.0.2/components/libraries/usbd/app_usbd_core.c:43:
/workspace/nrfspace/nrf5/nRF5_SDK_17.0.2/components/libraries/usbd/app_usbd_core.c:108:8: error: ‘APP_USBD_DEVICE_VER_SUB’ undeclared here (not in a function); did you mean ‘APP_USBD_DEVICE_VER_MINOR’?
/workspace/nrfspace/nrf5/nRF5_SDK_17.0.2/components/libraries/usbd/app_usbd_types.h:88:58: note: in definition of macro ‘APP_USBD_BCD_VER_MAKE’
/workspace/nrfspace/nrf5/nRF5_SDK_17.0.2/components/libraries/usbd/app_usbd_core.c:140:5: note: in expansion of macro ‘APP_USBD_CORE_DEVICE_DESCRIPTOR’
There were 1 build errors
make: *** [Makefile:22: release] Error 1
`

**Comment by ovidiusimionica** [comment]
Hi @aikrana  , I think I used nRF5_SDK_15.3.0. Try with that.

alternatively you could try to declare that 'APP_USBD_DEVICE_VER_SUB' in config/sdk_config.h to a decimal value e.g. 0 but I did not check it
